print('binary to octal:')
print(oct(0b1100))
print('binary to hexadecimal:')
print(hex(0x1000))
print('binary to decimal:')
print(0b101)
print('octal to binary')
print(bin(0o123))
print('hexadecimal to binary')
print(bin(0x1002))
print('decimal to binary')
print(bin(12))
print('octal to hexadecimal')
print(hex(0o143))
print('octal to decimal')
print(0o631)
print('hexa to octal:')
print(oct(0x433))
print('hexa to decimal:')
print(0x63)
print('decimal to octal:')
print(oct(64))
print('decimal to hexa:')
print(hex(589))